modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"
[[mods]] #mandatory
modId = "wormholes" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Wormholes" #mandatory
logoFile = "icon.png" #optional
credits = "The failure of ProtocolLib on Bukkit 1.8.9" #optional
authors = "cyberpwn, NextdoorPsycho" #optional
description = "This is a mod that allows you to create wormholes between two points, using Immersive portals as a portal core." #mandatory
[[dependencies.wormholes]] #optional
modId = "wormholes" #mandatory
mandatory = true #mandatory
versionRange = "0.0.0" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.wormholes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wormholes]]
modId = "immersive_portals" #mandatory
mandatory = true #mandatory
versionRange = "[0.0.0,)" #mandato

[[dependencies.wormholes]]
modId = "imm_ptl_core" #mandatory
mandatory = true #mandatory
versionRange = "[0.0.0,)" #mandatory

[[dependencies.wormholes]]
modId = "q_misc_util"
mandatory = true
versionRange = "[0.0.0,)"

